# Generated by Django 4.2.23 on 2025-07-12 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_ticket_unique_ticket_movie_session_order_row_seat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='auto_now_add',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
